version: "3.6"

volumes:
  data:
    driver: local

services:
  postgres:
    image: postgres:12-alpine
    container_name: postgres
    restart: unless-stopped
    environment:
      - POSTGRES_USER=cenotelie
      - POSTGRES_PASSWORD=cenotelie
      - POSTGRES_DB=cenotelie
    ports:
      - "6543:5432"
    volumes:
      - data:/var/lib/postgresql/data:Z
